# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CnX6CuRRujYEsBwaaCuG34M2RsOWZCpB
"""



# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# 
# st.title("Congratulations!")
# st.header("You've just created a website")
# st.balloons()
# st.snow()

!streamlit run app.py & npx localtunnel --port 8501
